modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Starter%20Kit"
logoFile="icon.png"

[[mods]]
modId="starterkit"
version="5.2"
displayName="Starter Kit"
displayURL="https://curseforge.com/minecraft/mc-mods/starter-kit"
authors="Rick South"
description='''Gives players who join the world for the first time configurable starter gear.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.starterkit]]
    modId="collective"
    mandatory=true
    versionRange="[6.57,)"
    ordering="NONE"
    side="BOTH"