modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Starter%20Kit"
logoFile="icon.png"

[[mods]]
modId="starterkit"
version="6.8"
displayName="Starter Kit"
displayURL="https://serilum.com/mod/starter-kit"
authors="Rick South"
description='''Gives players who join the world for the first time configurable starter gear.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.starterkit]]
    modId="collective"
    type="required"
    versionRange="[7.64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.starterkit]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "starterkit.mixins.json"